export const CONNECT = "CONNECT";
export const USERNAME = 'USERNAME';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_STATUS = 'UPDATE_EMPLOYEE_STATUS';
export const LOAD_ALL_EMPLOYEES = 'LOAD_ALL_EMPLOYEES';
export const LOAD_USER_FROM_EMPLOYEE_DETAILS = 'LOAD_USER_FROM_EMPLOYEE_DETAILS';
export const UPDATE_USER = 'UPDATE_USER';
